#This Dockerfile mounts the certs
FROM eclipse-temurin:21.0.7_6-jdk-alpine@sha256:2f2f553ce09d25e2d2f0f521ab94cd73f70c9b21327a29149c23a2b63b8e29a0 AS build-cert

ENV LANG=en_CA.UTF-8
ENV LANGUAGE=en_CA.UTF-8
ENV LC_ALL=en_CA.UTF-8
WORKDIR /app

RUN apk --no-cache add openssl

COPY get_certs.sh .

RUN chmod g+w /app && \
    chmod g+x get_certs.sh && \
    chmod g+w ${JAVA_HOME}/lib/security/cacerts

ENTRYPOINT ["sh", "get_certs.sh"]
