apiVersion: v1
kind: Service
metadata:
  name: {{ include "nr-oracle-service.name" . }}
  labels:
    {{- include "nr-oracle-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.app.envs.HTTP_PORT }}
      protocol: TCP
      name: http
  selector:
    {{- include "nr-oracle-service.selectorLabels" . | nindent 4 }}
