name: PR Validate

on:
  pull_request:
    types: [edited, opened, synchronize, reopened, ready_for_review]

concurrency:
  group: ${{ github.workflow }}-edit-${{ github.event.number }}
  cancel-in-progress: true

permissions: {}

jobs:
  validate:
    name: Validate PR
    if: (! github.event.pull_request.draft)
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: bcgov/actions/pr-validate@6763b12e9c5e7548fe0e63a63e16fe01f0f33b91 # v0.7.0
        with:
          add_markdown: |
            ---

            Thanks for the PR!

            This PR deploys to namespace `${{ vars.OC_NAMESPACE }}` as release `${{ github.event.repository.name }}-${{ github.event.number }}`.

            Once merged, code will be promoted via the [Merge Workflow](https://github.com/${{ github.repository }}/actions/workflows/merge.yml).
